backend:
  name: git-gateway
  branch: master
# publish_mode: editorial_workflow
media_folder: assets/img/portfolio
collections:
  - name: "posts"
    label: "Portfolio"
    folder: "_posts"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: "Title", name: "title"}
      - {label: "Subtitle", name: "subtitle"}
      - {label: "Poster", name: "poster"}
      - {label: "Website", name: "website"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

